//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gdb2epub.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\epub\\res\\irsans.ttf")]
        public string MainFontPath {
            get {
                return ((string)(this["MainFontPath"]));
            }
            set {
                this["MainFontPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\inetpub\\epub\\res\\cover-image.png")]
        public string CoverImagePath {
            get {
                return ((string)(this["CoverImagePath"]));
            }
            set {
                this["CoverImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IranNastaliq, 40pt")]
        public global::System.Drawing.Font CoverFont {
            get {
                return ((global::System.Drawing.Font)(this["CoverFont"]));
            }
            set {
                this["CoverFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string ExternalFTPServer_Host {
            get {
                return ((string)(this["ExternalFTPServer_Host"]));
            }
            set {
                this["ExternalFTPServer_Host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("root")]
        public string ExternalFTPServer_Username {
            get {
                return ((string)(this["ExternalFTPServer_Username"]));
            }
            set {
                this["ExternalFTPServer_Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExternalFTPServer_Password {
            get {
                return ((string)(this["ExternalFTPServer_Password"]));
            }
            set {
                this["ExternalFTPServer_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/home")]
        public string ExternalFTPServer_RootPath {
            get {
                return ((string)(this["ExternalFTPServer_RootPath"]));
            }
            set {
                this["ExternalFTPServer_RootPath"] = value;
            }
        }
    }
}
